### PR TITLE
Updating the template and adding tests.

### PR DESCRIPTION
**Pull request by darron**
Just fixing the template and adding tags.

Also adding TestKitchen tests.

### CODE REVIEW

**Comment by darron** [comment]
Not sure if it's easiest to merge here and add to your PR or do it on the other side.

But I saw your PR and added a few things - let me know if you've got any questions.

**Comment by wk8** [comment]
Thanks @darron!

Updating my PR to include your changes.

**Comment by wk8** [comment]
Updated https://github.com/DataDog/chef-datadog/pull/238, closing this.

**Comment by darron** [comment]
Thanks!

**Pull request closed without merging**
